spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/catsgram
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

catsgram:
  image-directory: "images"